- name: Setup Desktop Environment dan VNC
  run: |
    # Menginstal desktop environment (XFCE - ringan dan cepat)
    sudo apt-get update
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y xfce4 xfce4-goodies

    # Menginstal VNC server
    sudo apt-get install -y tightvncserver

    # Menginstal noVNC (untuk akses via browser)
    sudo apt-get install -y novnc websockify python3-websockify

    # Mengkonfigurasi password VNC
    mkdir -p ~/.vnc
    echo "${{ secrets.VNC_PASSWORD }}" | vncpasswd -f > ~/.vnc/passwd
    chmod 600 ~/.vnc/passwd

    # Mengkonfigurasi startup script VNC
    cat > ~/.vnc/xstartup << 'EOF'
    #!/bin/bash
    xrdb $HOME/.Xresources
    startxfce4 &
    EOF
    chmod +x ~/.vnc/xstartup

    # Memulai VNC server
    vncserver :1 -geometry 1280x800 -depth 24

    # Menyiapkan noVNC (akses melalui browser)
    websockify -D --web=/usr/share/novnc/ 6080 localhost:5901

    echo "VNC server berjalan pada port 5901"
    echo "noVNC tersedia pada port 6080"
